- name: Copy output to file
  copy:
    content: "{{ active_standby_guest_pairs }}"
    dest: "{{ TMP }}/active_standby_guest_pairs.json"
  tags:
    - post-upgrade-guests

- name: Run the python script to compare the active and standby statuses
  shell: python3 compare.py 
  args:
    chdir: "{{ SCRIPTS }}"    
  tags:
    - post-upgrade-guests