
- name: Assign one of the VCMP hosts as standby host before the standby successful upgrade
  set_fact:
    standby_host : True
  tags:
    - always


- name: List the standby_host fact
  debug:
    msg: "{{ standby_host }}"
  tags:
    - always
