

# - name: Wait for the REST api for "{{ item }}" to be available
#   bigip_wait:
#     provider:
#       server: "{{ item }}"
#       user: "{{ username }}"
#       password: "{{ password }}"
#       validate_certs: no
#   delegate_to: localhost
#   tags:
#     - upgrade-hosts




- name: Collect BIG-IP facts to determine VCMP guests
  bigip_device_info:
    gather_subset:
      - devices
    provider:
      server: "{{ item }}"
      user: "{{ username }}"
      password: "{{ password }}"
      validate_certs: no
  register: guest_pairs
  delegate_to: localhost
  tags:
    - always

- name: Printing out the First and second Device in the VCMP HA pair
  vars:
  set_fact:
    first_device: "{{ guest_pairs.devices[0].hostname }}"
    second_device: "{{ guest_pairs.devices[1].hostname }}"
  tags:
    - always


- name: Populate the active standby pairing for comparison later
  set_fact:
    active_standby_guest_pairs: "{{ active_standby_guest_pairs|default({}) | combine({first_device:second_device}) }}"
  loop: "{{ guest_pairs.devices }}"
  tags:
    - always