- name: Sleep for 300 seconds to account for the vcmp guest to come back
  wait_for:
    timeout: 300
  delegate_to: localhost
  tags:
    - upgrade-hosts
    
- name: Wait for "{{ item }}" to come back after deploy mode 
  bigip_wait:
    provider:
      server: "{{ item }}"
      user: "{{ username }}"
      password: "{{ password }}"
      timeout: 3600
      validate_certs: no
  delegate_to: localhost
  tags:
    - upgrade-hosts
